jwt:
  secret: kdosdireladskvsadfkeialwjafkldoepfwfndsnvldsfuwoekmlsdflsffdjskiefaejasdfefasfdvadeavdcvadsfeafgssgadfafadsfeafdaadfe

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: asdf1234
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        sql: debug